export const packagesDetails = [
  {
    id: 1,
    title: 'WM Package 1',
    price: 700,
    dishes: [
      'Chicken Korma / Chicken Karahi',
      'Chicken Biryani / Chicken Pulao',
      'Roghni Naan',
      'Raita',
      'Fresh green salad',
      'Dessert (1 from selection)',
    ],
  },
  {
    id: 2,
    title: 'WM Package 2',
    price: 900,
    dishes: [
      'Chicken Korma / Chicken Achari',
      'Mutton Biryani / Mutton Pulao',
      'Roghni Naan',
      'Raita',
      'Fresh green salad',
      'Dessert (1 from selection)',
    ],
  },
  {
    id: 3,
    title: 'WM Package 3',
    price: 800,
    dishes: [
      'Mutton Korma',
      'Chicken Biryani / Kashmiri Pulao',
      'Roghni Naan',
      'Raita',
      'Fresh green salad',
      'Dessert (1 from selection)',
    ],
  },
  {
    id: 4,
    title: 'WM Package 4',
    price: 850,
    dishes: [
      'Mutton Karahi',
      'Chicken Biryani / Chicken Pulao',
      'Roghni Naan',
      'Raita',
      'Fresh green salad',
      'Dessert (1 from selection)',
    ],
  },
  {
    id: 5,
    title: 'WM Package 5',
    price: 1000,
    dishes: [
      'Chicken Achari / Chicken Karahi',
      'Puri & Halwa Suji / Pathoora',
      'Channa Bhaji',
      'Roghni Naan',
      'Raita',
      'Fresh green salad',
      'Dessert (1 from selection)',
    ],
  },
  {
    id: 6,
    title: 'WM Package 6',
    price: 11000,
    dishes: [
      'Puri or Pathoora, Channa, Bhajji',
      'Halwa Sujji',
      'Chicken Sheekh Kebab / Chicken Tikka Boti',
      'Roghni Naan',
      'Raita',
      'Fresh green salad',
      'Dessert (1 from selection)',
    ],
  },
];

export const desserts = [
  'Fruit Trifle',
  'Firni',
  'Kulfa',
  'Icecream',
  'Falooda',
  'Zarda',
];

export const corporateMenu = [
  {
    title: 'CM Package 1',
    id: 1,
    price: 1500,
    dishes: [
      "Prawn's Tempura",
      'Chicken Boti',
      'Chicken Seekh Kebab',
      'Mutton Qorma',
      'Chicken Ginger',
      'Mutton Pulao',
      'Assorted Salads',
      'Green Tea / Coffee / Tea',
    ],
  },
  {
    title: 'CM Package 2',
    id: 2,
    price: 1600,
    dishes: [
      'Deep fried prawns',
      'Mutton lamb chops',
      'Chicken cheese boti',
      'Mutton kunna',
      'Chicken karahi',
      'Chicken chowmein',
      'Assorted Salads',
      'Green Tea / Coffee / Tea',
    ],
  },
  {
    title: 'CM Package 3',
    id: 3,
    price: 1800,
    dishes: [
      'Batter fried prawns',
      'Fish tikka',
      'Chicken boti (boneless)',
      'Mutton karahi',
      'Chicken jalfarezi',
      'Fried chicken',
      'Szchwan chicken st',
      'Assorted Salads',
      'Green Tea / Coffee / Tea',
    ],
  },
];
